stages:
- test
- docs

test:
  stage: test
  image: python:3.6
  before_script:
    - pip install tox
  variables:
    TOXENV: py,codecov
  script:
    - tox
  coverage: /TOTAL.+ ([0-9]{1,3}%)/
  artifacts:
    paths:
      - htmlcov
  tags:
    - private-ci

test-lint:
  stage: test
  image: python:3.6
  variables:
    TOXENV: lint
  before_script:
    - pip install tox
  script:
    - tox
  tags:
    - private-ci

test-docs:
  stage: test
  image: python:3.6
  variables:
    TOXENV: docs
  before_script:
    - pip install tox
  script:
    - tox
  tags:
    - private-ci

docs:
  stage: docs
  image: python:3.6
  before_script:
    - pip install -e .[doc]
  script:
    - sphinx-build -b html docs docs/_build/html
  artifacts:
    paths:
      - docs/_build/html
  tags:
    - private-ci