stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: test
    os: linux
    python: 3.5
    env: TOXENV=py,codecov
  # - stage: test
  #  os: linux
  #  python: 3.6
  #  env: TOXENV=py,codecov
  # - stage: test
  #  python: 3.6
  #  env: TOXENV=lint
  # - stage: test
  #  python: 3.6
  #  env: TOXENV=docs
  - stage: release
    python: 3.6
    deploy:
      provider: pypi
      user: nmvalera
      before_install: false
      install: false
      script: echo "Releasing to pypi.org..."
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: BAEtzBrxJWMNwKCFuw8wMd989PURe2tIoTKbfPv24W4D1bjxVTwOnSGRvdwLCviPj2heynUBGKe/JYj2Qn3fpHhPNg5lMsi2SvwLEtyvEgkkDg/6wBVVlDwds6vEJHuQzqtlABUrGF4KlSHlv+RJi/y8J9selitsK01xE7m8p/Q8mCtZwOBVBrOqjgyp+0lSUniomM6cfT6e9h5FdJb6D2OjQQdaFDSNtH/WdoKO5kxgwtpNZObyBC3citWyhHc0tpY9v5KP0WZ+Rpux3Qy60FhLBaRzDU25nEO6MHMZblelJfqJyhJW1rkhiJY/yw88iPurRFPB8p7SeEkwHW1TFjp/SrGYRKi3wBDDZRszreBkkawuPlc1x7dZqg0/Eu1WPnJDoB4mlEC9bQdaW7ie9fwn7tn61VIp0iteF3kyHfVjIZA1tOdc2eopofaJGesgpK1NQnabqVBBIfls1GfmZXTDA+B/vrKzfw2wbmu7GLTK5ZVLZgD/Dg52UL8yYWP+gngZ+MhQDOY3pS2OdYxf6+JUaZKYnHS6rhGDydlU/w0NczmvVNmngW9CzcXx0nVX6wUQbyjhtRAf0IInbq0FTiQvb1xjAEmUWwhwnqRwfhGuJA3tZV5qEcc1I7iEk90aRY7ga8bSWe9m8Co4W3t4LGRxsEJ9/3U69Gk97uSgEOs=
d