stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: release
    python: 3.6
    before_install: false
    install: false
    script: skip
    deploy:
      provider: pypi
      user: nmvalera
      distributions: sdist bdist_wheel
      password:
        secure: HqCL3sVtFO7YpWx65Tqi7Eqmx37U0h+Z5qXi8tZNP7EqvZRsDi7A4vKBXWuAb0scAUHfYMccOzPPQbDpsupzaDeqwTsdaUmvcKodvKY627wfDqEcRcsRge2heFN2Ru2YXNUK8vJ2hY0rNaXg3t7BtN0k0m1ZKXlHgKBkkD4gCJPKpG+G+XLGp/l4X4B2pWHhnld8KOTHNE0esZoURJF0PwXTbIoLFb8eFJKD4DsHgWoyjjV4CfmgwNe77PUaQCP7aaMw6NSh2+DGqqOH5BTV7TtezqM49h/0nI/QYhGkiqpMq2GxdFmm11GQ9riv+jQ2GO/GghRUEOrSWrPT5wJhp/DvMEald34vuuLobfa3F5qKQ9HpDzEJqOwz57AEXtiA4TdjkJoLH7d8hoWHcIedwN3eAc1e47je186bVnzbuwPsKADeGsnjFKL5P3ilNKLXOID7aKCnn5EFRXQl2aUvq53hCqdS/fJNkn+nvPuyiHobYimt4PnZFjUCRGDs7+UjBVnp6sdQ8XsfywRnJo9HT+WTMZ3k4tdzYmJ1Q3XaU65jNRvjnLpiJrr+bNHcPTCb6ROKytQj5sa0HnF/BpZl6MBuiSAMubZ4vrObBXK6253efeaz1XyoVgaW9NScfgTm8LZXILRGe1aHHiJYLU+YL8cDN24I2olUOAT4GHVM1sY=
