stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: release
    python: 3.6
    before_install: false
    install: false
    script: skip
    deploy:
      provider: pypi
      user: nmvalera
      distributions: sdist bdist_wheel
      password:
        secure: Eaqjray/9wM7HHNylZNHVBrpGn1y4iaFwWryb6GR4Oh5wog+QCj35DQTR4NPsSfC+c06w5ilfHPkRemgSMVobT14OUbXdaVW5ttZmt4wvs2inhQrmfem95yuA4FGLktCHYVs48cGcmg1lN3tD7vbBlFVSin+SssxLSxCbVlzYXEq+F4Qq8QpmSVTjqMa3cCUYHO+8K/CiBdsECNfd3iqXcBvXhEhtZk5s36diFXkSIn02jEgCHFjQpxdvrvL5idUoI/n+htWEQuLA3s6MuyY7DfzCSWy19qhKfT4BDypT0OKCL1UPUzpz5gHR/FEWAIkPX1tHzgLivr8hroKjrnqC9rw1o74+yCLiBrnRQZeFFcwjG+Zu/jcavlb+xxaSxltaJWeG98LG3F8UpsA3+1pBgOfjhuM2zIi8lT/UDlCC8+al8ddJg692BRrbX2MLs1Ty/5o6kdW+LUY6vw72/FRC6so0alIJ7V7grVKC8PbTFagK14WjqVYQfTdTb9jyhaKSpNeGgkMNWk2D+gMc5/uCr761LFf3BIKT+9uk9jAqdVA0bHkjAwegLpcJ1y6mqAwTAGtyr9yHq7tRmvNpQhLS7avJEOcKUt5Mz1XalKQL5FNud1X+aNj2bjFpMTQItYFZECkPyKeZIb2vr5KSi4mZEoG24r3YmFAd+aza+M98Mk=
