stages:
  - test
  - release

sudo: false

language: python

cache: pip

install:
  - pip install tox

script: tox

jobs:
  include:
    - stage: test
      os: linux
      python: 3.5
      env: TOXENV=py,codecov
    - stage: test
      os: linux
      python: 3.6
      env: TOXENV=py,codecov
    - stage: test
      os: linux
      python: 3.5
      env: TOXENV=py,codecov
    - stage: test
      python: 3.6
      env: TOXENV=lint
    - stage: test
      python: 3.6
      env: TOXENV=docs
    - stage: release
      script: echo releasing