stages:
  - test
  - release

sudo: false

language: python

cache: pip

matrix:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py,codecov
    - os: linux
      python: 3.6
      env: TOXENV=py,codecov
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install tox

script: tox

jobs:
  - stage: release
    script: echo "releasing"