stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: release
    python: 3.6
    before_install: false
    install: false
    script: skip
    deploy:
      provider: pypi
      user: nmvalera
      distributions: sdist bdist_wheel
      password:
        secure: hsOtTURl5jjS//T161sSl/TAOw9sNhg9rqdljuySvCaVRr835kjcA2NtRtsh/j3dwYioWLjdx7r7zvkLyZnPj4c05liMCwSnU6EI4hKTAVUMTbc2Derup3aMJdL1w5JIQmsScSS4P0a32E24vcd3dR3xEKA0wmamdnbspNTSLRsO1ATcih2RIo1IDnQW9cKpF/RJughrmY/ZoSQb2auWYi9xymoDxYrwK/9iT5vvqnicnsLnzEWYFGhAp4GOvjSpK5yHU+uAgojhmqjD2OMlnc7IAERwPvURZarDy8iPMsdGYJGcAcl8IXnYhbAiZaJS69bbHz+fwtqhrEqNGV5pxruuZ70eg1mjGkPR5362dJDTRAqgoRMKNUErrKZv4EDtgR/LMm/2sjtGuhA75BW7lWuRpTsbdmZruZcvs8RGRsSuJ67aw8OMtVU65yhq06rQA5SaLvzZ/842Y3kYwb3xTV7t8kZ2yg/1Pl4UX0NsCukDfbaQQEZbw0sXdCrZShD8bpv8Q8bgaeiLJO7dXk+t4ggC7SjrkH+RwJLuP2tXz0MqcCaJqis/uY/WOBfeQIRcOqLBn0JQ8DMDbU0v3LttLeJDZq17yMWP3JdYUrjUigCdwjzsXWB4ApMnE/lIANx1Rzc52FDfqWKF9eu7X1hJMW1ulXIghwmVzf+3LjAy4+E=
