stages:
  - test
  - pypi

sudo: false

language: python

cache: pip

matrix:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py,codecov
    - os: linux
      python: 3.6
      env: TOXENV=py,codecov
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install tox

script: tox

jobs:
  - stage: pypi
    if: tag IS present
    python: 3.6
    deploy:
      provider: pypi
      user: nmvalera
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: