stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: release
    python: 3.6
    before_install: false
    install: false
    script: skip
    deploy:
      provider: pypi
      user: nmvalera
      distributions: sdist bdist_wheel
      password:
        secure: k9h92knFr9+G186AS0UdVEi7bqiugd2vLEJkeihyKMrlIASPCZhaJCmsuHDQlSr10OQjCoBNZLLBu7m6KLZrJyjY7GbntqmhhyvxQ+3/Zh8xJdOFriZHzVyEzBGf7w9XCIP48LmnDBFbdWax6OFRWUjCGecVYo1kvB8ohYVv/cx9LvwDuWOtGzsMBleDiaNDK4IiXnnHq6mNeKYUa3J8t/a2QkVujvRG1zWN7fBY+qjFh7JctLGc+MQkP242Hcp5FhIofPCUpdMwM2DhB7Jk4x6BtziOHDQicwfpd9D1ajadG2rs2A0vrjeNzmG+Tk/vMspUygmMvXQE1zZsXBqi2s7DYnLck2w9I44uiLXS8JEiSH3rSy7Kxzg42q6psoZqUj5/2lUO5RJ62dr/3tlVLoJoZk0GM8D0S7nrZQ5JjVzeh4LW8UxY+OI64iWFwPIfyI/a9RMLm+Z8MwfNo+unlfkcDbgRZzzXKQ3XNG/JWfn/2RBW8dBgL1XNCLfu3VmMq/PJw1S5pJy3zcHHO+JxPpJaO8JESd/Slym9++yX0zt+fgUXOOSPg37boZjBwlGiybWT0RjlOyR7OtiMr4EZkGKOvcPVvNJnzJnct5tSf0MClGnu4viH6BLptHItobrq1iQ1EBQQwzvH3pcahnDv2IwpMlRwxV6ZHNNUi4WgPtA=
