stages:
- test
- release
sudo: false
language: python
cache: pip
install:
- pip install tox
script: tox
jobs:
  include:
  - stage: release
    python: 3.6
    before_install: false
    install: false
    script: skip
    deploy:
      provider: pypi
      user: nmvalera
      distributions: sdist bdist_wheel
      password:
        secure: TLqi1gmwH5vzfcV1ehEvVjrf/t0N9byh5WoqtdnR/aMJ29Gg4rPqIh7kgZsIPJ2UQsbn9Bj1yVqQn0vGriM2NPlN3OhFFPX6fUEYQrmnQ4mGSdIXzHN5KO9s1t5cb7cJ/LAYoBw81fly0E/tEoSi2bNs97MIE21Oo/JyJeGsGxXVGn1HB6yVikZaQU38vclDSqQuqcRL8564FehwfxAT0iABAGUPIKbhaEOsP0zOUY4CQBkAKc09+GFsqRHfRkE04h7qbOsZ1eW4eKKt77s2Zgd2okLc+YiAh6/Gq/tIbfb69UHy03iKpyaAugjUc1QW9nnxXg6Ivcg2YiPzmkzjrX/MwSsKFQtwkFVWrDiDcSjK5gtJW3RK6kvAi3Qvyec+NAWjIZisTFkakrSQweo6/mjyXBIe3bpQG/bWjzTw/8egN51Z+i6+tlA3rbs4qsFdGVuTZxoB4HpkCkmf/j53mCnRoMKo3mvfPmmmCaZBzWTbPYr1nBDmqXUNaSh2JAVDDoeLoVEyZcqc4ZsF/CGjoEgq5lchKduNpKvsbjJTNgM+OBRFQTjOR/Ai9LP198eLTyNOSMMAfjwviEY3RzL3fWJfvT2JKn/MPZJ8VU3y92+6qvt8xYzKqLZWfsVXtM2Mu1VZ4bYszjhOssaXnChL1EC6HDj3DzMdzJVhM8xVFqU=
x